### ISSUE TITLE
Error when clicking the refresh button

### ISSUE THREAD

**Issue by merlebleue** [piMoll/swissgeodownloader#8]
Hello ! Thank you very much for your plugin, which seems very usefull. I get this error when I click on the refresh button, any idea why ?

I have no problem loading the basemap in grey

``` 
IndexError: list index out of range
             
             
             Traceback (most recent call last):
              File "C:\Users/Julien.Ars/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\swissgeodownloader\api\apiCallerTask.py", line 55, in run
              self.output = self.apiRef.getDatasetList(self)
              File "C:\Users/Julien.Ars/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\swissgeodownloader\api\datageoadmin.py", line 76, in getDatasetList
              dataset.licenseLink = [link['href'] for link in ds['links']
             IndexError: list index out of range
```

**Comment by piMoll** [comment]
Hello! Thanks very much for the report. I already fixed this bug and uploaded a new plugin version to the QGIS repository. 
It is currently being checked and will soon be available. I guess next monday you should be able to update.

**Comment by merlebleue** [comment]
Perfect ! Thank you very much :)

**Comment by merlebleue** [comment]
Yep, installing the new ersion from github solves the problem. Thank you very much !
